export { default as Header } from './Header'
export { default as NavBar } from './NavBar'
export { default as SideBar } from './SideBar'
export { default as Main } from './Main'
export { default as Footer } from './Footer'
